spring.application.name=kiosk
server.port=22511
server.servlet.context-path=/kiosk

spring.mvc.static-path-pattern=/static/**

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML5
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.check-template=true
spring.thymeleaf.template-resolver-order=0

spring.datasource.hikari.driver=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.jdbc-url=jdbc:postgresql://172.16.1.3:5432/namhae
spring.datasource.username=rino
spring.datasource.password=rino1234



