spring.application.name=kiosk
server.port=22511
server.servlet.context-path=/kiosk

spring.mvc.static-path-pattern=/static/**

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML5
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.check-template=true
spring.thymeleaf.template-resolver-order=0

spring.datasource.hikari.driver=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.pool-n`ame=HikariCP
spring.datasource.hikari.jdbc-url=jdbc:postgresql://YOUR_DB_HOST:5432/YOUR_DB_NAME
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD


